CREATE TABLE [dbo].[tblUPWPAction]
(
[ActionID] [int] NOT NULL,
[Action] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tblUPWPAction] ADD CONSTRAINT [PK_tblUPWPAction] PRIMARY KEY CLUSTERED ([ActionID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idx_tblUPWPAction] ON [dbo].[tblUPWPAction] ([ActionID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
