CREATE TABLE [dbo].[tblPR]
(
[id] [int] NULL,
[sponsoring_agency_id] [smallint] NULL,
[user_id] [smallint] NULL,
[status] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[proj_id] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[title] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contact_first_name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contact_last_name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contact_email] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[alt_contact_first_name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[alt_contact_last_name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[alt_contact_email] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[progress] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[delays] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[design_status] [smallint] NULL,
[pe_complete] [bit] NULL,
[environmental_approval] [bit] NULL,
[row_certification] [bit] NULL,
[contract_awarded] [bit] NULL,
[construction_complete] [bit] NULL,
[pe_complete_on] [datetime] NULL,
[environmental_approval_on] [datetime] NULL,
[row_certification_on] [datetime] NULL,
[contract_awarded_on] [datetime] NULL,
[construction_complete_on] [datetime] NULL,
[pe_obligation_on] [datetime] NULL,
[row_obligation_on] [datetime] NULL,
[construction_obligation_on] [datetime] NULL,
[other_obligation_on] [datetime] NULL,
[estimate_changing] [bit] NULL,
[updated_estimate] [int] NULL,
[administrative] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[submitted_at] [datetime] NULL,
[accepted_at] [datetime] NULL,
[created_at] [datetime] NULL,
[updated_at] [datetime] NULL,
[contact_phone] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[alt_contact_phone] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pe_obligation_na] [bit] NULL,
[row_obligation_na] [bit] NULL,
[construction_obligation_na] [bit] NULL,
[other_obligation_na] [bit] NULL,
[contact_title] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[alt_contact_title] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[on_schedule] [bit] NULL,
[project_type] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[planning_funds_obligation_on] [datetime] NULL,
[stand_alone_remaining_work_to_completion] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pe_remaining_work_to_completion] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[row_remaining_work_to_completion] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[permits_and_agreements] [bit] NULL,
[permits_and_agreements_on] [datetime] NULL,
[construction_remaining_work_to_completion] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_bill_submitted_on] [datetime] NULL,
[last_bill_submitted_na] [bit] NULL,
[next_bill_submittal_on] [datetime] NULL,
[next_bill_submittal_na] [bit] NULL,
[project_advertised_on] [datetime] NULL,
[project_advertised] [bit] NULL,
[env_doc_level] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[current_step] [tinyint] NULL,
[row_plans_approved] [bit] NULL,
[row_plans_approved_on] [datetime] NULL,
[row_pfe_or_tce_prepared] [bit] NULL,
[row_pfe_or_tce_prepared_on] [datetime] NULL,
[row_relocation] [bit] NULL,
[row_relocation_approved_by_wsdot] [bit] NULL,
[row_relocation_approved_by_wsdot_on] [datetime] NULL,
[contract_complete] [bit] NULL,
[contract_complete_on] [datetime2] NULL,
[can_obligate_early] [bit] NULL,
[early_ob_phase_1] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[early_ob_date_phase_1] [datetime2] NULL,
[early_ob_phase_2] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[early_ob_date_phase_2] [datetime2] NULL
) ON [PRIMARY]
GO
